// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJuIGAPfK-oND76CbremzEBU3BFSuNjr0',
    appId: '1:776707766838:web:b0e79c6054d189b2cff697',
    messagingSenderId: '776707766838',
    projectId: 'saas-msaa',
    authDomain: 'saas-msaa.firebaseapp.com',
    storageBucket: 'saas-msaa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeHEBDOutI8psOm8KiT5OhsaIT_L65hFA',
    appId: '1:776707766838:android:55b42707c4952b60cff697',
    messagingSenderId: '776707766838',
    projectId: 'saas-msaa',
    storageBucket: 'saas-msaa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3NejIkKt0No6hzoZ_9mUh91zzi6zg740',
    appId: '1:776707766838:ios:108e96079a13dc1acff697',
    messagingSenderId: '776707766838',
    projectId: 'saas-msaa',
    storageBucket: 'saas-msaa.appspot.com',
    iosBundleId: 'com.example.saasMsaa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3NejIkKt0No6hzoZ_9mUh91zzi6zg740',
    appId: '1:776707766838:ios:d2d7c71532e22ba1cff697',
    messagingSenderId: '776707766838',
    projectId: 'saas-msaa',
    storageBucket: 'saas-msaa.appspot.com',
    iosBundleId: 'com.example.saasMsaa.RunnerTests',
  );
}
